version: "3"
services:
  dtree_model:
    build: .
    volumes:
      - ./model_inputs_outputs:/opt/model_inputs_outputs
    ports:
      - 8080:8080
    working_dir: /opt/ModellingLogistic
    command: tail -f /dev/null # keep the container running
    
